import styles from './Footer.module.css';

const Footer = () => {
  return (
    <footer className={styles.footer}>
      <p className={styles.made}>Made by <a className={styles.link} href="https://github.com/bowman025">bowman025</a>.</p>
      <p className={styles.disclaimer}>Disclaimer: All images were generated by AI.</p>
    </footer>
  );
};

export default Footer;
